[package]
name = "ringring-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
log = "0.4.28"

[dependencies.tokio]
version = "1.48.0"
features = ["macros", "rt-multi-thread"]

[dependencies.serenity]
version = "0.12.4"
